# Header Menu
menu:
  Home: /
  Projects: /projects/
  Blog: /archives/ # can set archive-dir in root config to custom value
  # Contact: /contact/
  About: /about/
   
# rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true # whether or not to load the fancybox library

# Integrations
disqus_shortname: tangram7
google_analytics: UA-88107707-1
swiftype_install_key: 

# Social
social:
  github: https://github.com/xiongyihui

# Miscellaneous
color_scheme: green   # options: blue, gray, green, orange, red, turquoise
favicon: /favicon.ico # path from root of hexo site
# twitter_widget_id: "" # as a string, from https://twitter.com/settings/widgets
# twitter_username: YihuiXiong # twitter username without the @
default_author: "Yihui Xiong"

about: To create, to have fun.

